In [ ]:
import pandas as pd

**Load Dataset**

In [13]:
from google.colab import files
uploaded = files.upload()

Saving placement.csv to placement (1).csv

In [ ]:
df = pd.read_csv("placement.csv")

**Display first 5 rows**

In [ ]:
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

**Check missing values**

In [ ]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

**Handle missing values**

In [ ]:
# Fill missing salary values with 0 because students who are not placed do not have a salary
df["salary"] = df["salary"].fillna(0)

**Recheck Missing Values**

In [ ]:
df.isnull().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

**Remove duplicates**

In [ ]:
# Remove duplicate records
df = df.drop_duplicates()

**Clean text columns**

In [ ]:
text_cols = [
    "gender",
    "ssc_b",
    "hsc_b",
    "hsc_s",
    "degree_t",
    "workex",
    "specialisation",
    "status"
]

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

**rename columns**

In [ ]:
df.rename(columns={
    "ssc_p": "SSC_Percentage",
    "hsc_p": "HSC_Percentage",
    "degree_p": "Degree_Percentage"
}, inplace=True)

**Create a new useful column**

In [ ]:
df["Average_Academic_Score"] = (
    df["SSC_Percentage"] +
    df["HSC_Percentage"] +
    df["Degree_Percentage"]
) / 3

**Export the cleaned dataset**

In [14]:
df.to_csv("cleaned_dataset.csv", index=False)